### PR TITLE
Styling of hard-seltzers page

### LINKED ISSUE #16: Footer: Style Footer

### PR DESCRIPTION
**Pull request by cziegeler**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Test URLs:
- Before: https://main--sazerac-99brandparty--hlxsites.hlx.page/hard-seltzer-pairings
- After: https://issue-16--sazerac-99brandparty--hlxsites.hlx.page/hard-seltzer-pairings

### CODE REVIEW

**Comment by RemoLiechti** [comment]
there's no anchers for apples. bananas etc.
from within liquers, sometimes, there is a link to those.
see https://99brandparty.com/products/99-apples/ where you can press the 'see hard seltzer pairings' button that goes to https://99brandparty.com/hard-seltzer-pairings/#apples

**Review by RemoLiechti — CHANGES_REQUESTED** [review]
add anchors

**Comment by RemoLiechti** [comment]
and you probably linked the wrong task? #16 is closed and was footer!

**Comment by cziegeler** [comment]
@RemoLiechti This is a draft and by no means finished yet. We first need #32 before we have all the data to display on this page.
I updated the issue number

**Review by RemoLiechti — APPROVED** [review]

**Review by karlpauls — APPROVED** [review]

**Pull request merged**
